# -*- coding: utf-8 -*-
"""Question 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-O3TzPLHp4WIi3zHdNi9lWkBHCgSN1mk
"""

from collections import Counter
s = "New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3."
c = Counter(s.split())
for k,v in c.items():
    print(k,':',v)

