# -*- coding: utf-8 -*-
"""Question 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBmhTuGLK5z-igggcfG4c4RO2OOABDU8
"""

def pattern(n):
    for i in range(n):
        print(' ' * i, end='')
        for j in range(n, i, -1):
            print(j, end='')
        print(' ', end='')
        for k in range(i + 1, n + 1):
            print(k, end='')
        print()

if __name__ == '__main__':
    pattern(5)

