# -*- coding: utf-8 -*-
"""Question 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rx6j_aR8R-IPpEb4mfVUwXN9T3wU_eSA
"""

def uncommonWords(str1, str2):
    str1 = str1.split()
    str2 = str2.split()
    # create a set of words from both the strings
    set1 = set(str1)
    set2 = set(str2)
    # create a set of words that are not present in both the strings
    set3 = set1.difference(set2)
    set4 = set2.difference(set1)
    # create a set of uncommon words
    set5 = set3.union(set4)
    # print the uncommon words
    print(set5)

if __name__ == '__main__':
    str1 = "learn programming at includehelp"
    str2 = "learn python programming language"
    uncommonWords(str1, str2)

