# -*- coding: utf-8 -*-
"""Question 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LGYIJMGkHl28YhBVvzt6TRv_m6slcGD-
"""

def camelCase(string):
    words = string.split()
    words[0] = words[0].lower()
    for i in range(1, len(words)):
        words[i] = words[i][0].upper() + words[i][1:]
    return ''.join(words)


string = "Hello World"
print(camelCase(string))

