# -*- coding: utf-8 -*-
"""Question 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RJzgKoFO3Su9_8od-WoBFdQgAUjpE_bY
"""

x,y = 3,5
print([[i*j for j in range(y)] for i in range(x)])

