# -*- coding: utf-8 -*-
"""Question 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YJ9t-_aLnD0wHvEs67Gd6cvebz8M4kVZ
"""

def pattern(n):
    for i in range(n,0,-1):
        for j in range(1,i+1):
            print(j, end=" * ")
        print()

if __name__ == "__main__":
    pattern(4)

